# Google App Engine deployment configuration for the Battleship server
runtime: nodejs
env: flex

env_variables:
  CORS: '*'
  SERVER_PORT: 8080

# Use only a single instance, so that this local-memory-only Battleship application will work consistently with multiple users.
# TODO Add ability to work across multiple instances, extra-instance messaging system or data store will be needed.
manual_scaling:
  instances: 1

network:
  session_affinity: true

entrypoint: 'node server/dist/server.js'
